'use client';
import { useMemo, useState } from 'react';
import Link from 'next/link';
import WalletBar from '../../components/WalletBar';
import {SiteHeader, SiteFooter} from '../../components/home/SiteChrome';
import styles from '../../components/home/Home.module.css';
import { useLocale } from '../../components/LocaleContext';
import {CardDialog} from '../../components/home/CardDialog';
import {CardFacts} from '../../components/home/CardFacts';
import {LibraryCardFace} from '../../components/home/LibraryCardFace';
import { CHARACTER_CARDS } from '../../lib/characterCards';
const CHARACTER_CARD_COUNT = Object.keys(CHARACTER_CARDS).length;
import Dialog from '../../components/Dialog';
import { useCollection } from '../../components/CollectionContext';
import { CARDS } from '../../lib/cards';
import { HEROES } from '../../lib/heroes';
import { DECKS } from '../../lib/decks';
import { deckError, loadCustomDeck, saveCustomDeck } from '../../lib/deckbuilder';
import { useNfts } from '../../components/NftContext';
import { useImperivmWallet } from '../../components/WalletContext';
import { explorerUrl } from '../../lib/solana/devnet';
export default function CollectionPage() {
  const { t, cardName, cardText, heroName, errorText } = useLocale();
  const collection = useCollection();
  const nfts = useNfts(), wallet = useImperivmWallet();
  const [inspected, setInspected] = useState<string | null>(null);
  const [filter, setFilter] = useState('All'), [query, setQuery] = useState(''), [mode, setMode] = useState<'catalog' | 'owned' | 'nft' | 'characters'>('catalog');
  const [hero, setHero] = useState('whale'), [deck, setDeck] = useState<string[]>([]), [building, setBuilding] = useState(false), [notice, setNotice] = useState<string | null>(null), [trade, setTrade] = useState(false);
  const localOwned = collection.snapshot?.owned ?? {};
  const owned = Object.fromEntries(Object.keys(CARDS).map(id => [id, (localOwned[id] ?? 0) + (nfts.counts[id] ?? 0)]).filter(([, count]) => Number(count) > 0)) as Record<string, number>;
  const inventory = mode === 'nft' ? nfts.counts : owned;
  const catalogMode = mode === 'catalog' || mode === 'characters';
  const visible = Object.values(CARDS).filter(c => (filter === 'All' || c.faction === filter) && (catalogMode || inventory[c.id] > 0) && (mode !== 'characters' || !!CHARACTER_CARDS[c.id]) && `${cardName(c.id)} ${cardText(c.id)} ${c.name} ${c.text}`.toLowerCase().includes(query.toLowerCase()));
  const counts = useMemo(() => deck.reduce<Record<string, number>>((all, id) => ({ ...all, [id]: (all[id] ?? 0) + 1 }), {}), [deck]);
  const error = deckError(deck, !catalogMode ? inventory : undefined);
  function add(id: string) { const limit = Math.min(CARDS[id].rarity === 'legendary' ? 1 : 2, !catalogMode ? inventory[id] ?? 0 : 2); if (deck.length < 30 && (counts[id] ?? 0) < limit) { setDeck(d => [...d, id]); setNotice(null); } }
  function save() { try { saveCustomDeck(hero, deck); setNotice('Deck saved in this browser. Ready for battle.'); } catch (e) { setNotice(e instanceof Error ? e.message : 'Browser storage is unavailable.'); } }
  return <div className={styles.shell}><SiteHeader active="collection" /><main className={`${styles.hubMain} collection-page`}>
    <nav className="collection-nav"><Link href="/">{t('← Главная', '← Home')}</Link><Link href="/packs">{t('Паки', 'Packs')}</Link><Link href="/leaderboard">{t('Победы', 'Victories')}</Link><button onClick={() => setTrade(true)}>{t('Обмен ↗', 'Trade ↗')}</button></nav>
    <p className="eyebrow">{t('Соберите свой легион', 'Assemble your legion')}</p><h1 className="font-display text-4xl sm:text-5xl gold-text">{t('Коллекция', 'The collection')}</h1>
    <p className="integration-note">{t(`${Object.keys(CARDS).length} игровых карт, четыре стартовые колоды и ${CHARACTER_CARD_COUNT} новых персонажей со способностями и связками. Открывайте паки, чтобы пополнить `, `${Object.keys(CARDS).length} playable cards, four starter decks and ${CHARACTER_CARD_COUNT} new characters with abilities and synergies. Packs grow your `)}{collection.snapshot?.mode === 'idos' ? 'iDos' : t('локальную', 'local')} {t('коллекцию.', 'collection.')}</p>
    <div className="collection-wallet"><strong>{collection.snapshot?.rug ?? '—'} $RUG</strong><span>{Object.keys(owned).length}/{Object.keys(CARDS).length} {t('видов карт собрано', 'card types collected')}</span><button className="secondary-button" onClick={() => { setBuilding(b => !b); setNotice(null); }}>{building ? t('Закрыть редактор', 'Close deckbuilder') : t('Собрать колоду', 'Build a deck')}</button></div>
    {collection.error && <p className="integration-error" role="status">{errorText(collection.error)} <button onClick={() => void collection.refresh()}>{t('Повторить', 'Retry')}</button> · <button onClick={() => void collection.useLocalDemo()}>{t('Локальное демо', 'Use local demo')}</button></p>}
    <details className={styles.optionalNft}><summary>{t('Коллекционные NFT · devnet (необязательно)', 'Collectible NFTs · devnet (optional)')}</summary><WalletBar /><div className="integration-panel mt-5"><p className="text-mint text-sm">{t('Владение NFT в devnet', 'Devnet NFT ownership')} · {nfts.cards.length} {t('подтверждённых карт', 'verified cards')}</p><p className="integration-note">{wallet.owner ? nfts.deployment ? t('Карты открываются только для NFT этого кошелька из настроенной коллекции Genesis с подходящими метаданными.', 'Only NFTs owned by this wallet, in the configured Genesis collection, with matching card metadata unlock cards here.') : t('Коллекция Genesis пока не настроена.', 'Genesis collection is not configured yet.') : t('Подключите Phantom для проверки NFT Genesis. Демо всегда доступно.', 'Connect Phantom to read Genesis NFTs. Demo play stays available.')}</p><div className="dialog-actions"><button className="secondary-button" disabled={!wallet.owner || !nfts.deployment || nfts.busy} onClick={() => void nfts.refresh()}>{nfts.busy ? t('Чтение NFT…', 'Reading NFTs…') : t('Проверить владение NFT', 'Refresh NFT ownership')}</button><Link href="/devnet" className="secondary-button">{t('Настройка Genesis', 'Genesis setup')}</Link></div>{nfts.error && <p className="integration-error" role="status">{errorText(nfts.error)}</p>}</div></details>
    <div className="collection-filters"><div className="mode-tabs"><button aria-pressed={mode === 'catalog'} onClick={() => setMode('catalog')}>{t(`Игровые карты · ${Object.keys(CARDS).length}`, `Playable cards · ${Object.keys(CARDS).length}`)}</button><button aria-pressed={mode === 'characters'} onClick={() => setMode('characters')}>{t(`Новые персонажи · ${CHARACTER_CARD_COUNT}`, `New characters · ${CHARACTER_CARD_COUNT}`)}</button><button aria-pressed={mode === 'owned'} onClick={() => setMode('owned')}>{t('Моя коллекция', 'My collection')}</button><button aria-pressed={mode === 'nft'} onClick={() => setMode('nft')}>{t('NFT в devnet', 'Devnet NFTs')}</button></div><input aria-label={t('Поиск карт', 'Search cards')} placeholder={t('Поиск по легиону…', 'Search your legion…')} value={query} onChange={e => setQuery(e.target.value)} /><select aria-label={t('Фильтр фракций', 'Filter faction')} value={filter} onChange={e => setFilter(e.target.value)}>{['All', 'DeFi', 'NFT', 'DePIN', 'Meme'].map(f => <option key={f} value={f}>{f === 'All' ? t('Все', 'All') : f}</option>)}</select></div>
    {mode === 'characters' && <div className={styles.expansionNotice}><strong>{t('Agora After Hours · 50 игровых персонажей', 'Agora After Hours · 50 playable characters')}</strong><p>{t('Уже в четырёх стартовых колодах. Откройте карту: там характеристики, способности и условия связки. Можно добавить в свою колоду.', 'Already in the four starter decks. Inspect a card for stats, abilities and synergy conditions, or add it to your own deck.')}</p><span>{t(`Показано ${visible.length} из ${CHARACTER_CARD_COUNT}`, `Showing ${visible.length} of ${CHARACTER_CARD_COUNT}`)}</span></div>}<div className={building ? 'collection-workspace' : ''}><div className={styles.nativeCollectionGrid}>{visible.map(card => <div key={card.id} className={styles.nativeCollectionCard}><button type="button" className={styles.hubCard} aria-label={t(`Рассмотреть карту «${cardName(card.id)}»`, `Inspect ${cardName(card.id)}`)} onClick={event => {event.currentTarget.focus({preventScroll:true}); setInspected(card.id);}}><LibraryCardFace id={card.id}/><CardFacts id={card.id}/></button><div className="collection-card-caption"><span>{owned[card.id] ? t(`В коллекции ×${owned[card.id]}`, `Owned ×${owned[card.id]}`) : t('Демо-каталог', 'Demo catalog')}{nfts.counts[card.id] > 0 && <><br /><a className="nft-owned-tag" href={explorerUrl(nfts.cards.find(nft => nft.cardId === card.id)!.address)} target="_blank" rel="noreferrer">NFT ×{nfts.counts[card.id]} · {t('проверено', 'verified')} ↗</a></>}</span>{building && <button aria-label={t(`Добавить ${cardName(card.id)} в колоду`, `Add ${card.name} to deck`)} disabled={deck.length >= 30 || (counts[card.id] ?? 0) >= Math.min(card.rarity === 'legendary' ? 1 : 2, !catalogMode ? inventory[card.id] ?? 0 : 2)} onClick={() => add(card.id)}>{t('В колоду', 'Add')} · {counts[card.id] ?? 0}</button>}</div></div>)}</div>
    {building && <aside className="deck-panel"><h2 className="font-display text-xl text-gold">{t('Ваша колода', 'Your deck')} · {deck.length}/30</h2><label className="block mt-4 text-xs text-lavender">{t('Герой', 'Hero')}<select value={hero} onChange={e => { setHero(e.target.value); setDeck([]); setNotice(null); }}>{Object.values(HEROES).map(h => <option key={h.id} value={h.id}>{heroName(h.id)}</option>)}</select></label><div className="dialog-actions"><button className="secondary-button" onClick={() => { setMode('catalog'); setDeck([...DECKS[hero]]); setNotice(null); }}>{t('Готовая колода', 'Use preset')}</button><button className="secondary-button" onClick={() => { setDeck(loadCustomDeck(hero) ?? []); setNotice(null); }}>{t('Загрузить сохранённую', 'Load saved')}</button><button className="secondary-button" onClick={() => setDeck([])}>{t('Очистить', 'Clear')}</button></div><div className="deck-list thin-scroll">{Object.entries(counts).sort(([a], [b]) => CARDS[a].cost - CARDS[b].cost).map(([id, count]) => <button key={id} onClick={() => { setDeck(d => { const copy = [...d]; copy.splice(copy.lastIndexOf(id), 1); return copy; }); setNotice(null); }} aria-label={t(`Убрать одну карту ${cardName(id)}`, `Remove one ${CARDS[id].name}`)}><span>{CARDS[id].cost} · {cardName(id)}</span><b>×{count} −</b></button>)}</div><p className="integration-note">{error ? errorText(error) : t('Колода готова · 30 карт. До 2 копий каждой карты; легендарной — 1.', 'Valid deck · 30 cards. Up to 2 copies of each card; 1 for each legendary.')}</p><button className="primary-button w-full mt-4" disabled={!!error} onClick={save}>{t('Сохранить колоду', 'Save deck')}</button>{notice && <p role="status" className="integration-note">{errorText(notice)}</p>}{!error && notice?.startsWith('Deck saved') && <Link className="primary-button block mt-3" href={`/game?hero=${hero}&deck=custom`}>{t('В бой с этой колодой →', 'Play this deck →')}</Link>}</aside>}</div>
    {!visible.length && <p className="py-12 text-center text-lavender">{t('Нет карт по этому запросу. Измените поиск или откройте каталог.', 'No cards match this filter. Change the search or explore the catalog.')}</p>}
  </main><SiteFooter />{inspected && <CardDialog id={inspected} onClose={() => setInspected(null)} />}{trade && <Dialog title={t('Обмен · предпросмотр devnet', 'Trade · devnet preview')} onClose={() => setTrade(false)}><p className="text-sm text-parchment/80">{t('IMPERIVM Genesis пока не представлен на маркетплейсе. Реальный обмен в этом предпросмотре devnet недоступен.', 'IMPERIVM Genesis has no marketplace listing yet. This devnet preview does not support real trading.')}</p><Link className="secondary-button inline-block mt-5" href="/devnet">{t('Посмотреть настройку devnet →', 'View devnet setup →')}</Link></Dialog>}</div>;
}
