/**
 * IMPERIVM — card content v1.
 *
 * Four factions (DeFi / NFT / DePIN / Meme), plus shared edict expansions.
 * Vanilla minion curve: cost N ≈ N+1 total stats; cards with effects sit below it.
 * All rules text is in English with imperial-crypto flavor.
 * Effect kinds used are exactly those from lib/engine/types.ts.
 */
import type { CardDef } from './engine/types';

export const CARDS: Record<string, CardDef> = {
  'senate-censure': {
    id:'senate-censure',name:'Senate Censure',faction:'DeFi',rarity:'rare',cost:2,type:'spell',
    spell:{kind:'weaken-random-enemy',amount:1},text:'Reduce a random enemy fighter’s attack by 1, to a minimum of 0.',
  },
  'restoration-rite': {
    id:'restoration-rite',name:'Restoration Rite',faction:'NFT',rarity:'rare',cost:2,type:'spell',
    spell:{kind:'heal-own-minions',amount:2},text:'Restore 2 health to every friendly fighter, up to their maximum health.',
  },
  // Olympus: public preparation, a payoff, and room for the opponent to answer.
  'agora-expansion': {
    id:'agora-expansion', name:'Agora Expansion', faction:'DePIN', rarity:'rare', cost:3, type:'spell',
    spell:{kind:'expand-board',amount:1}, text:'Instant. Permanently add one fighter slot, up to seven. Scaling the agora, not the hype.',
  },
  'diamond-aegis': {
    id:'diamond-aegis', name:'Diamond Aegis', faction:'NFT', rarity:'rare', cost:3, type:'spell',
    spell:{kind:'buff-own',attack:0,health:2}, text:'Instant. Give all your fighters +0/+2. Diamond hands hold the line.',
  },
  'hermes-relayer': {
    id:'hermes-relayer', name:'Hermes Relayer', faction:'DePIN', rarity:'rare', cost:3, type:'minion', attack:2, health:2,
    battlecry:{kind:'draw',amount:1},
    ultimate:{condition:'faction-plays',count:1,faction:'DePIN',name:'Relay Alpha',nameRu:'Альфа-сигнал',effect:{kind:'draw',amount:2}},
    text:'Battlecry: Draw one. Ultimate — if you already played a DePIN card this turn, draw two instead. Alpha at the speed of gossip.',
  },
  'athena-diamond-guard': {
    id:'athena-diamond-guard', name:'Athena of Diamond Hands', faction:'NFT', rarity:'legendary', cost:6, type:'minion', attack:3, health:5, taunt:true,
    ultimate:{condition:'faction-allies',count:2,faction:'NFT',name:'Diamond Phalanx',nameRu:'Алмазная фаланга',effect:{kind:'buff-own',attack:1,health:1}},
    text:'Taunt. Ultimate — if two other NFT fighters survived since your previous turn, give your whole army +1/+1. Never sells the bottom.',
  },
  'zeus-liquidator': {
    id:'zeus-liquidator', name:'Zeus the Liquidator', faction:'DeFi', rarity:'legendary', cost:8, type:'minion', attack:5, health:5,
    battlecry:{kind:'damage-all-enemy-minions',amount:1},
    ultimate:{condition:'staked',count:2,name:'Olympian Margin Call',nameRu:'Маржин-колл Олимпа',effect:{kind:'damage-all-enemy-minions',amount:3}},
    text:'Battlecry: Deal one to all enemy fighters. Ultimate — if two of your established fighters are staked, deal three instead. Olympus liquidates your leverage.',
  },
  'hades-rugkeeper': {
    id:'hades-rugkeeper', name:'Hades the Rugkeeper', faction:'Meme', rarity:'legendary', cost:7, type:'minion', attack:4, health:5,
    battlecry:{kind:'damage-enemy-treasury',amount:1},
    ultimate:{condition:'faction-plays',count:2,faction:'Meme',name:'Underworld Exit Liquidity',nameRu:'Выход в ликвидность',effect:{kind:'damage-enemy-treasury',amount:4}},
    text:'Battlecry: Deal one to the enemy treasury. Ultimate — if you already played two Meme cards this turn, deal four instead. Exit liquidity is eternal.',
  },

  // ---------------------------------------------------------------- DeFi
  'lending-legionnaire': {
    id: 'lending-legionnaire',
    name: 'Lending Legionnaire',
    faction: 'DeFi',
    rarity: 'common',
    cost: 1,
    type: 'minion',
    attack: 1,
    health: 1,
    text: 'Lends his shield. Never his denarii.',
  },
  'amm-centurion': {
    id: 'amm-centurion',
    name: 'AMM Centurion',
    faction: 'DeFi',
    rarity: 'common',
    cost: 2,
    type: 'minion',
    attack: 2,
    health: 2,
    text: 'A constant product of blood and iron. x * y = k, and k is Rome.',
  },
  'liquidation-officer': {
    id: 'liquidation-officer',
    name: 'Liquidation Officer',
    faction: 'DeFi',
    rarity: 'common',
    cost: 3,
    type: 'minion',
    attack: 2,
    health: 2,
    lifesteal: true,
    battlecry: { kind: 'damage-random-enemy', amount: 1 },
    text: 'Lifesteal. Battlecry: Deal 1 damage to a random enemy minion. Your collateral was delicious.',
  },
  'frontrun-bot': {
    id: 'frontrun-bot',
    name: 'Frontrun Bot',
    faction: 'DeFi',
    rarity: 'rare',
    cost: 3,
    type: 'minion',
    attack: 2,
    health: 2,
    priority: true,
    battlecry: { kind: 'counter-mempool' },
    text: 'Priority. Battlecry: Remove the highest-cost enemy mempool spell. Your mempool order is his business.',
  },
  'priority-fee': {
    id: 'priority-fee',
    name: 'Priority Fee',
    faction: 'DeFi',
    rarity: 'rare',
    cost: 1,
    type: 'spell',
    priority: true,
    spell: { kind: 'gain-gas', amount: 1 },
    text: 'Priority. Gain 1 gas. Pay the skipper. Skip the line.',
  },
  'yield-farmer': {
    id: 'yield-farmer',
    name: 'Yield Farmer',
    faction: 'DeFi',
    rarity: 'common',
    cost: 3,
    type: 'minion',
    attack: 1,
    health: 3,
    halvingPeriod: 4,
    text: 'Every 4 blocks: +1/+1. Emissions halve. Hunger does not.',
  },
  'staking-pool': {
    id: 'staking-pool',
    name: 'Staking Pool',
    faction: 'DeFi',
    rarity: 'rare',
    cost: 4,
    type: 'minion',
    attack: 1,
    health: 4,
    battlecry: { kind: 'gain-gas', amount: 2 },
    text: 'Battlecry: Gain 2 gas. Stake here. Compound forever. Staked minions pay +1 gas each at turn start.',
  },
  'flash-loan': {
    id: 'flash-loan',
    name: 'Flash Loan',
    faction: 'DeFi',
    rarity: 'common',
    cost: 2,
    type: 'spell',
    spell: { kind: 'draw', amount: 2 },
    text: 'Draw 2 cards. Borrow the treasury. Return it tomorrow.',
  },
  'impermanent-guard': {
    id: 'impermanent-guard',
    name: 'Impermanent Guard',
    faction: 'DeFi',
    rarity: 'epic',
    cost: 5,
    type: 'minion',
    attack: 3,
    health: 3,
    taunt: true,
    battlecry: { kind: 'heal-treasury', amount: 4 },
    text: 'Taunt. Battlecry: Restore 4 to your treasury. Losses impermanent. Loyalty eternal.',
  },
  'imperator-liquidus': {
    id: 'imperator-liquidus',
    name: 'Imperator Liquidus',
    faction: 'DeFi',
    rarity: 'legendary',
    cost: 7,
    type: 'minion',
    attack: 5,
    health: 4,
    battlecry: { kind: 'damage-all-enemy-minions', amount: 2 },
    text: 'Battlecry: Deal 2 damage to all enemy minions. All debts to Rome are settled in blood.',
  },

  // ------------------------------------------------------------------ NFT
  'pixel-squire': {
    id: 'pixel-squire',
    name: 'Pixel Squire',
    faction: 'NFT',
    rarity: 'common',
    cost: 1,
    type: 'minion',
    attack: 1,
    health: 1,
    text: 'Born of right-click.',
  },
  'whitelist-scout': {
    id: 'whitelist-scout',
    name: 'Whitelist Scout',
    faction: 'NFT',
    rarity: 'common',
    cost: 1,
    type: 'minion',
    attack: 1,
    health: 1,
    battlecry: { kind: 'draw', amount: 1 },
    text: 'Battlecry: Draw a card. Guaranteed spot. Guaranteed glory.',
  },
  'profile-pic-phalanx': {
    id: 'profile-pic-phalanx',
    name: 'Profile-Pic Phalanx',
    faction: 'NFT',
    rarity: 'common',
    cost: 2,
    type: 'minion',
    attack: 1,
    health: 2,
    taunt: true,
    text: 'Taunt. Right-click. Save. Enlist.',
  },
  'trait-reroll': {
    id: 'trait-reroll',
    name: 'Trait Reroll',
    faction: 'NFT',
    rarity: 'common',
    cost: 2,
    type: 'spell',
    spell: { kind: 'buff-own', attack: 1, health: 0 },
    text: 'Give all your minions +1 attack. New trait just dropped.',
  },
  'floor-sweeper': {
    id: 'floor-sweeper',
    name: 'Floor Sweeper',
    faction: 'NFT',
    rarity: 'common',
    cost: 3,
    type: 'minion',
    attack: 2,
    health: 2,
    battlecry: { kind: 'draw', amount: 1 },
    text: 'Battlecry: Draw a card. Sweeps the floor. Keeps the alpha.',
  },
  'ape-praetorian': {
    id: 'ape-praetorian',
    name: 'Ape Praetorian',
    faction: 'NFT',
    rarity: 'rare',
    cost: 4,
    type: 'minion',
    attack: 2,
    health: 3,
    halvingPeriod: 3,
    text: 'Every 3 blocks: +1/+1. Diamond hands. Paper enemies.',
  },
  'minting-press': {
    id: 'minting-press',
    name: 'Minting Press',
    faction: 'NFT',
    rarity: 'rare',
    cost: 5,
    type: 'minion',
    attack: 2,
    health: 4,
    battlecry: { kind: 'summon', cardId: 'pixel-squire' },
    text: 'Battlecry: Summon a Pixel Squire. The press never sleeps.',
  },
  'reveal-ceremony': {
    id: 'reveal-ceremony',
    name: 'Reveal Ceremony',
    faction: 'NFT',
    rarity: 'epic',
    cost: 4,
    type: 'spell',
    spell: { kind: 'damage-all-enemy-minions', amount: 2 },
    text: 'Deal 2 damage to all enemy minions. The art was inside us all along.',
  },
  'blue-chip-basilisk': {
    id: 'blue-chip-basilisk',
    name: 'Blue-Chip Basilisk',
    faction: 'NFT',
    rarity: 'epic',
    cost: 6,
    type: 'minion',
    attack: 4,
    health: 3,
    rush: true,
    text: 'Rush. Gaze upon the floor price.',
  },
  'genesis-pfp': {
    id: 'genesis-pfp',
    name: 'Genesis PFP',
    faction: 'NFT',
    rarity: 'legendary',
    cost: 7,
    type: 'minion',
    attack: 4,
    health: 4,
    battlecry: { kind: 'buff-own', attack: 1, health: 1 },
    text: 'Battlecry: Give all your minions +1/+1. The first face of the Empire.',
  },

  // ---------------------------------------------------------------- DePIN
  'antenna-auxilia': {
    id: 'antenna-auxilia',
    name: 'Antenna Auxilia',
    faction: 'DePIN',
    rarity: 'common',
    cost: 1,
    type: 'minion',
    attack: 1,
    health: 1,
    text: 'Carries the signal through the storm.',
  },
  'mesh-messenger': {
    id: 'mesh-messenger',
    name: 'Mesh Messenger',
    faction: 'DePIN',
    rarity: 'common',
    cost: 2,
    type: 'minion',
    attack: 1,
    health: 2,
    text: 'Every packet finds its legion.',
  },
  'relay-runner': {
    id: 'relay-runner',
    name: 'Relay Runner',
    faction: 'DePIN',
    rarity: 'rare',
    cost: 3,
    type: 'minion',
    attack: 2,
    health: 2,
    battlecry: { kind: 'draw', amount: 1 },
    text: 'Battlecry: Draw a card. Faster than gossip.',
  },
  'node-sentinel': {
    id: 'node-sentinel',
    name: 'Node Sentinel',
    faction: 'DePIN',
    rarity: 'common',
    cost: 3,
    type: 'minion',
    attack: 1,
    health: 3,
    halvingPeriod: 3,
    text: 'Every 3 blocks: +1/+1. Proof of uptime.',
  },
  'bandwidth-barbarian': {
    id: 'bandwidth-barbarian',
    name: 'Bandwidth Barbarian',
    faction: 'DePIN',
    rarity: 'common',
    cost: 4,
    type: 'minion',
    attack: 3,
    health: 2,
    text: 'He eats latency for breakfast.',
  },
  'hotspot-hoplite': {
    id: 'hotspot-hoplite',
    name: 'Hotspot Hoplite',
    faction: 'DePIN',
    rarity: 'rare',
    cost: 4,
    type: 'minion',
    attack: 1,
    health: 4,
    taunt: true,
    text: 'Taunt. Stake him. He holds the line — and the yield. Staked minions pay +1 gas each at turn start.',
  },
  'gps-gladiator': {
    id: 'gps-gladiator',
    name: 'GPS Gladiator',
    faction: 'DePIN',
    rarity: 'common',
    cost: 5,
    type: 'minion',
    attack: 3,
    health: 3,
    battlecry: { kind: 'damage-random-enemy', amount: 2 },
    text: 'Battlecry: Deal 2 damage to a random enemy minion. He always knows where you live.',
  },
  'solar-sapper': {
    id: 'solar-sapper',
    name: 'Solar Sapper',
    faction: 'DePIN',
    rarity: 'rare',
    cost: 3,
    type: 'spell',
    spell: { kind: 'damage-all-enemy-minions', amount: 2 },
    text: 'Deal 2 damage to all enemy minions. Harvested sunlight, weaponized.',
  },
  'firmware-phalanx': {
    id: 'firmware-phalanx',
    name: 'Firmware Phalanx',
    faction: 'DePIN',
    rarity: 'epic',
    cost: 6,
    type: 'minion',
    attack: 3,
    health: 4,
    battlecry: { kind: 'buff-own', attack: 1, health: 1 },
    text: 'Battlecry: Give all your minions +1/+1. Update installed. Morale upgraded.',
  },
  'the-grand-cartographer': {
    id: 'the-grand-cartographer',
    name: 'The Grand Cartographer',
    faction: 'DePIN',
    rarity: 'legendary',
    cost: 7,
    type: 'minion',
    attack: 4,
    health: 4,
    battlecry: { kind: 'gain-gas', amount: 2 },
    text: 'Battlecry: Gain 2 gas. His maps power the Empire.',
  },

  // ----------------------------------------------------------------- Meme
  'jeet-legion': {
    id: 'jeet-legion',
    name: 'Jeet Legion',
    faction: 'Meme',
    rarity: 'common',
    cost: 1,
    type: 'minion',
    attack: 1,
    health: 1,
    battlecry: { kind: 'damage-enemy-treasury', amount: 1 },
    text: 'Battlecry: Deal 1 damage to the enemy treasury. Paper hands. Iron panic.',
  },
  'gm-greeter': {
    id: 'gm-greeter',
    name: 'GM Greeter',
    faction: 'Meme',
    rarity: 'common',
    cost: 1,
    type: 'minion',
    attack: 1,
    health: 1,
    battlecry: { kind: 'heal-treasury', amount: 3 },
    text: 'Battlecry: Restore 3 to your treasury. Good morning, legion.',
  },
  dogen: {
    id: 'dogen',
    name: 'Dogen',
    faction: 'Meme',
    rarity: 'common',
    cost: 2,
    type: 'minion',
    attack: 2,
    health: 1,
    text: 'Much legion. Wow.',
  },
  'sandwich-attacker': {
    id: 'sandwich-attacker',
    name: 'Sandwich Attacker',
    faction: 'Meme',
    rarity: 'rare',
    cost: 2,
    type: 'minion',
    attack: 2,
    health: 1,
    priority: true,
    battlecry: { kind: 'damage-enemy-treasury', amount: 1 },
    text: 'Priority. Battlecry: Deal 1 damage to the enemy treasury. He eats the spread — and your lunch.',
  },
  pepito: {
    id: 'pepito',
    name: 'Pepito',
    faction: 'Meme',
    rarity: 'common',
    cost: 3,
    type: 'minion',
    attack: 2,
    health: 2,
    text: 'Rare. Green. Unstoppable.',
  },
  'pump-chaser': {
    id: 'pump-chaser',
    name: 'Pump Chaser',
    faction: 'Meme',
    rarity: 'common',
    cost: 4,
    type: 'minion',
    attack: 3,
    health: 2,
    battlecry: { kind: 'gain-gas', amount: 1 },
    text: 'Battlecry: Gain 1 gas. Buys the top. Every time.',
  },
  'diamond-hoarder': {
    id: 'diamond-hoarder',
    name: 'Diamond Hoarder',
    faction: 'Meme',
    rarity: 'rare',
    cost: 5,
    type: 'minion',
    attack: 2,
    health: 4,
    text: 'Staked hands never sell. Stake her: she cannot attack anyway, but she pays gas.',
  },
  'fud-hydra': {
    id: 'fud-hydra',
    name: 'FUD Hydra',
    faction: 'Meme',
    rarity: 'epic',
    cost: 6,
    type: 'minion',
    attack: 3,
    health: 4,
    battlecry: { kind: 'damage-all-enemy-minions', amount: 2 },
    text: 'Battlecry: Deal 2 damage to all enemy minions. Cut one FUD, two take its place.',
  },
  'to-the-moon-militia': {
    id: 'to-the-moon-militia',
    name: 'To-The-Moon Militia',
    faction: 'Meme',
    rarity: 'epic',
    cost: 7,
    type: 'minion',
    attack: 5,
    health: 3,
    battlecry: { kind: 'damage-enemy-treasury', amount: 3 },
    text: 'Battlecry: Deal 3 damage to the enemy treasury. One small step for memes.',
  },
  'rug-pull': {
    id: 'rug-pull',
    name: 'RUG PULL',
    faction: 'Meme',
    rarity: 'legendary',
    cost: 8,
    type: 'spell',
    spell: { kind: 'rugpull' },
    text: 'Destroy ALL minions on both boards. Veni. Vidi. Rugi.',
  },

  // ----------------------------------------------------- package 4A: Audit
  // Counter to RUG PULL. DeFi/rare, cost 3, Priority — when cast it
  // immediately pulls the highest-cost enemy mempool spell (RUG PULL
  // is cost 8, so it gets countered). On resolve the spell buffs the
  // caster's own board with +1/+1.
  audit: {
    id: 'audit',
    name: 'Audit',
    faction: 'DeFi',
    rarity: 'rare',
    cost: 3,
    type: 'spell',
    priority: true,
    spell: { kind: 'buff-own', attack: 1, health: 1 },
    text: 'Priority. Pull the highest-cost enemy mempool spell. On resolve: give your minions +1/+1. The ledger closes before the rug falls.',
  },
};
