/**
 * Fifty playable characters from the approved character-art-50 roster.
 *
 * Public setup is the source of their stronger arrival effects: established
 * staked fighters, faction fighters surviving an enemy turn, or earlier faction
 * plays in the current turn. Ultimates REPLACE Battlecry; they never stack with it.
 * Summoned helpers require a free slot and do not repeat their own Battlecry.
 * Existing game rules, original cards and NFT Genesis IDs are left unchanged.
 */
import type { CardDef } from './engine/types';

export const CHARACTER_CARDS: Record<string, CardDef> = {
  "collateral-squire": {
    "id": "collateral-squire", "name": "Collateral Squire",
    "faction": "DeFi", "rarity": "common", "cost": 1, "type": "minion",
    "attack": 1, "health": 1, "taunt": true,
    "text": "Taunt. The shield is collateral. The courage is not.",
  },
  "reserve-matron": {
    "id": "reserve-matron", "name": "Reserve Matron",
    "faction": "DeFi", "rarity": "common", "cost": 2, "type": "minion",
    "attack": 1, "health": 2,
    "battlecry": {"kind": "heal-treasury", "amount": 1},
    "ultimate": {"condition": "staked", "count": 1, "name": "Rainy-Block Reserve", "nameRu": "Резерв чёрного блока", "effect": {"kind": "heal-treasury", "amount": 4}},
    "text": "Battlecry: restore 1 health to your treasury. Combo — if at least 1 established friendly fighter is staked, restore 4 health to your treasury instead of the ordinary Battlecry. Emergency reserves are for rainy blocks.",
  },
  "interest-shepherd": {
    "id": "interest-shepherd", "name": "Interest Shepherd",
    "faction": "DeFi", "rarity": "common", "cost": 2, "type": "minion",
    "attack": 1, "health": 2, "halvingPeriod": 4,
    "text": "Every 4 blocks: +1/+1. The flock compounds while the market sleeps.",
  },
  "spread-duelist": {
    "id": "spread-duelist", "name": "Spread Duelist",
    "faction": "DeFi", "rarity": "common", "cost": 3, "type": "minion",
    "attack": 3, "health": 1, "rush": true, "lifesteal": true,
    "text": "Rush. Lifesteal. She takes the spread, not the fair fight.",
  },
  "slippage-netter": {
    "id": "slippage-netter", "name": "Slippage Netter",
    "faction": "DeFi", "rarity": "common", "cost": 2, "type": "minion",
    "attack": 1, "health": 1,
    "battlecry": {"kind": "weaken-random-enemy", "amount": 1},
    "text": "Battlecry: reduce a random enemy fighter’s attack by 1, to a minimum of 0. A tighter net means a smaller slip.",
  },
  "credit-lanternist": {
    "id": "credit-lanternist", "name": "Credit Lanternist",
    "faction": "DeFi", "rarity": "common", "cost": 3, "type": "minion",
    "attack": 1, "health": 2,
    "battlecry": {"kind": "draw", "amount": 1},
    "ultimate": {"condition": "staked", "count": 1, "name": "Collateral Illuminated", "nameRu": "Залог под светом", "effect": {"kind": "draw", "amount": 2}},
    "text": "Battlecry: draw 1 card. Combo — if at least 1 established friendly fighter is staked, draw 2 cards instead of the ordinary Battlecry. Reads the fine print by borrowed light.",
  },
  "amm-tidekeeper": {
    "id": "amm-tidekeeper", "name": "AMM Tidekeeper",
    "faction": "DeFi", "rarity": "rare", "cost": 4, "type": "minion",
    "attack": 1, "health": 4,
    "battlecry": {"kind": "heal-own-minions", "amount": 1},
    "ultimate": {"condition": "staked", "count": 1, "name": "Deep Reserve", "nameRu": "Глубокий резерв", "effect": {"kind": "buff-own", "attack": 0, "health": 1}},
    "text": "Battlecry: restore up to 1 health to every friendly fighter. Combo — if at least 1 established friendly fighter is staked, give every friendly fighter +0/+1 instead of the ordinary Battlecry. Keeps the pool from becoming a puddle.",
  },
  "margin-hoplite": {
    "id": "margin-hoplite", "name": "Margin Hoplite",
    "faction": "DeFi", "rarity": "rare", "cost": 4, "type": "minion",
    "attack": 2, "health": 3, "taunt": true,
    "ultimate": {"faction": "DeFi", "condition": "faction-allies", "count": 1, "name": "Margin of Safety", "nameRu": "Запас прочности", "effect": {"kind": "weaken-random-enemy", "amount": 2}},
    "text": "Taunt. Combo — if at least 1 other DeFi fighter survived the opponent’s turn, reduce a random enemy fighter’s attack by 2, to a minimum of 0. His margin of safety has a bronze edge.",
  },
  "mempool-usher": {
    "id": "mempool-usher", "name": "Mempool Usher",
    "faction": "DeFi", "rarity": "rare", "cost": 2, "type": "minion",
    "attack": 1, "health": 1,
    "battlecry": {"kind": "counter-mempool"},
    "text": "Battlecry: cancel the highest-cost edict in the enemy queue. Your expensive decree is not on the list.",
  },
  "liquidation-bailiff": {
    "id": "liquidation-bailiff", "name": "Liquidation Bailiff",
    "faction": "DeFi", "rarity": "rare", "cost": 5, "type": "minion",
    "attack": 3, "health": 2,
    "battlecry": {"kind": "damage-random-enemy", "amount": 1},
    "ultimate": {"faction": "DeFi", "condition": "faction-allies", "count": 2, "name": "Enforced Liquidation", "nameRu": "Принудительная ликвидация", "effect": {"kind": "damage-random-enemy", "amount": 4}},
    "text": "Battlecry: deal 1 damage to a random enemy fighter, or their treasury if there are none. Combo — if at least 2 other DeFi fighters survived the opponent’s turn, deal 4 damage to a random enemy fighter, or their treasury if there are none instead of the ordinary Battlecry. He collects after the legion has secured the court.",
  },
  "delta-sphinx": {
    "id": "delta-sphinx", "name": "Delta Sphinx",
    "faction": "DeFi", "rarity": "epic", "cost": 5, "type": "minion",
    "attack": 2, "health": 4, "taunt": true,
    "ultimate": {"condition": "staked", "count": 1, "name": "Yield Riddle", "nameRu": "Загадка доходности", "effect": {"kind": "draw", "amount": 2}},
    "text": "Taunt. Combo — if at least 1 established friendly fighter is staked, draw 2 cards. The riddle is easy. Keeping the collateral is not.",
  },
  "oracle-of-solvency": {
    "id": "oracle-of-solvency", "name": "Oracle of Solvency",
    "faction": "DeFi", "rarity": "epic", "cost": 6, "type": "minion",
    "attack": 2, "health": 4,
    "battlecry": {"kind": "gain-gas", "amount": 1},
    "ultimate": {"condition": "staked", "count": 2, "name": "Solvent Tomorrow", "nameRu": "Завтра без долгов", "effect": {"kind": "gain-gas", "amount": 3}},
    "text": "Battlecry: gain 1 order this turn. Combo — if at least 2 established friendly fighters are staked, gain 3 orders this turn instead of the ordinary Battlecry. Foresees one thing: you will need more orders.",
  },
  "poseidon-deep-liquidity": {
    "id": "poseidon-deep-liquidity", "name": "Poseidon of Deep Liquidity",
    "faction": "DeFi", "rarity": "legendary", "cost": 8, "type": "minion",
    "attack": 4, "health": 5, "taunt": true,
    "battlecry": {"kind": "heal-treasury", "amount": 4},
    "ultimate": {"condition": "staked", "count": 2, "name": "Deep Liquidity Tide", "nameRu": "Прилив глубокой ликвидности", "effect": {"kind": "buff-own", "attack": 1, "health": 2}},
    "text": "Taunt. Battlecry: restore 4 health to your treasury. Combo — if at least 2 established friendly fighters are staked, give every friendly fighter +1/+2 instead of the ordinary Battlecry. The tide rewards those who held their anchors.",
  },
  "clay-mint-apprentice": {
    "id": "clay-mint-apprentice", "name": "Clay Mint Apprentice",
    "faction": "NFT", "rarity": "common", "cost": 1, "type": "minion",
    "attack": 1, "health": 1,
    "battlecry": {"kind": "heal-own-minions", "amount": 1},
    "text": "Battlecry: restore up to 1 health to every friendly fighter. Fresh clay, fresh conviction.",
  },
  "provenance-scribe": {
    "id": "provenance-scribe", "name": "Provenance Scribe",
    "faction": "NFT", "rarity": "common", "cost": 2, "type": "minion",
    "attack": 1, "health": 1,
    "ultimate": {"faction": "NFT", "condition": "faction-allies", "count": 1, "name": "Verified Provenance", "nameRu": "Подтверждённое происхождение", "effect": {"kind": "draw", "amount": 2}},
    "text": "Combo — if at least 1 other NFT fighter survived the opponent’s turn, draw 2 cards. A surviving original makes the next edition credible.",
  },
  "mosaic-mender": {
    "id": "mosaic-mender", "name": "Mosaic Mender",
    "faction": "NFT", "rarity": "common", "cost": 3, "type": "minion",
    "attack": 1, "health": 3,
    "battlecry": {"kind": "heal-own-minions", "amount": 2},
    "text": "Battlecry: restore up to 2 health to every friendly fighter. A crack is not a floor price.",
  },
  "gallery-gatekeeper": {
    "id": "gallery-gatekeeper", "name": "Gallery Gatekeeper",
    "faction": "NFT", "rarity": "common", "cost": 2, "type": "minion",
    "attack": 0, "health": 4, "taunt": true,
    "text": "Taunt. No right-clickers beyond this point.",
  },
  "patina-curator": {
    "id": "patina-curator", "name": "Patina Curator",
    "faction": "NFT", "rarity": "common", "cost": 3, "type": "minion",
    "attack": 2, "health": 1,
    "ultimate": {"faction": "NFT", "condition": "faction-allies", "count": 1, "name": "Patina of Patience", "nameRu": "Патина терпения", "effect": {"kind": "buff-own", "attack": 0, "health": 1}},
    "text": "Combo — if at least 1 other NFT fighter survived the opponent’s turn, give every friendly fighter +0/+1. Surviving the market is its own collectible trait.",
  },
  "blank-canvas-sentinel": {
    "id": "blank-canvas-sentinel", "name": "Blank Canvas Sentinel",
    "faction": "NFT", "rarity": "common", "cost": 2, "type": "minion",
    "attack": 2, "health": 1, "halvingPeriod": 5,
    "text": "Every 5 blocks: +1/+1. An unfinished masterpiece still grows.",
  },
  "reveal-diviner": {
    "id": "reveal-diviner", "name": "Reveal Diviner",
    "faction": "NFT", "rarity": "rare", "cost": 4, "type": "minion",
    "attack": 2, "health": 2,
    "battlecry": {"kind": "damage-all-enemy-minions", "amount": 1},
    "ultimate": {"faction": "NFT", "condition": "faction-plays", "count": 1, "name": "Burning Reveal", "nameRu": "Огненное раскрытие", "effect": {"kind": "damage-all-enemy-minions", "amount": 2}},
    "text": "Battlecry: deal 1 damage to every enemy fighter. Combo — if you already played at least 1 NFT card this turn, deal 2 damage to every enemy fighter instead of the ordinary Battlecry. The second mint reveals the fire underneath.",
  },
  "soulbound-companion": {
    "id": "soulbound-companion", "name": "Soulbound Companion",
    "faction": "NFT", "rarity": "rare", "cost": 3, "type": "minion",
    "attack": 1, "health": 3, "taunt": true,
    "ultimate": {"faction": "NFT", "condition": "faction-allies", "count": 1, "name": "Bound by Survival", "nameRu": "Связаны выживанием", "effect": {"kind": "heal-own-minions", "amount": 3}},
    "text": "Taunt. Combo — if at least 1 other NFT fighter survived the opponent’s turn, restore up to 3 health to every friendly fighter. Stays for the friends, not the floor.",
  },
  "royalty-chorister": {
    "id": "royalty-chorister", "name": "Royalty Chorister",
    "faction": "NFT", "rarity": "rare", "cost": 4, "type": "minion",
    "attack": 1, "health": 3,
    "battlecry": {"kind": "gain-gas", "amount": 1},
    "ultimate": {"faction": "NFT", "condition": "faction-plays", "count": 1, "name": "Royalty Encore", "nameRu": "Роялти на бис", "effect": {"kind": "gain-gas", "amount": 2}},
    "text": "Battlecry: gain 1 order this turn. Combo — if you already played at least 1 NFT card this turn, gain 2 orders this turn instead of the ordinary Battlecry. The chorus pays once. No perpetual royalties.",
  },
  "unbroken-marble-warden": {
    "id": "unbroken-marble-warden", "name": "Unbroken Marble Warden",
    "faction": "NFT", "rarity": "rare", "cost": 5, "type": "minion",
    "attack": 2, "health": 4, "taunt": true,
    "battlecry": {"kind": "heal-treasury", "amount": 2},
    "ultimate": {"faction": "NFT", "condition": "faction-allies", "count": 2, "name": "Unbroken Collection", "nameRu": "Нерушимая коллекция", "effect": {"kind": "buff-own", "attack": 0, "health": 2}},
    "text": "Taunt. Battlecry: restore 2 health to your treasury. Combo — if at least 2 other NFT fighters survived the opponent’s turn, give every friendly fighter +0/+2 instead of the ordinary Battlecry. Keeps an intact collection through a bear market.",
  },
  "medusa-of-missing-mints": {
    "id": "medusa-of-missing-mints", "name": "Medusa of Missing Mints",
    "faction": "NFT", "rarity": "epic", "cost": 6, "type": "minion",
    "attack": 3, "health": 3,
    "battlecry": {"kind": "weaken-random-enemy", "amount": 2},
    "ultimate": {"faction": "NFT", "condition": "faction-plays", "count": 1, "name": "Petrified Floor", "nameRu": "Окаменевший флор", "effect": {"kind": "weaken-random-enemy", "amount": 4}},
    "text": "Battlecry: reduce a random enemy fighter’s attack by 2, to a minimum of 0. Combo — if you already played at least 1 NFT card this turn, reduce a random enemy fighter’s attack by 4, to a minimum of 0 instead of the ordinary Battlecry. Missed the mint? Try moving with those paper hands.",
  },
  "palimpsest-guardian": {
    "id": "palimpsest-guardian", "name": "Palimpsest Guardian",
    "faction": "NFT", "rarity": "epic", "cost": 6, "type": "minion",
    "attack": 2, "health": 5, "lifesteal": true,
    "ultimate": {"faction": "NFT", "condition": "faction-allies", "count": 2, "name": "Living Palimpsest", "nameRu": "Живой палимпсест", "effect": {"kind": "buff-own", "attack": 1, "health": 1}},
    "text": "Lifesteal. Combo — if at least 2 other NFT fighters survived the opponent’s turn, give every friendly fighter +1/+1. Writes a stronger army over the surviving draft.",
  },
  "persephone-second-mint": {
    "id": "persephone-second-mint", "name": "Persephone of the Second Mint",
    "faction": "NFT", "rarity": "legendary", "cost": 8, "type": "minion",
    "attack": 4, "health": 5,
    "battlecry": {"kind": "summon", "cardId": "pixel-squire"},
    "ultimate": {"faction": "NFT", "condition": "faction-allies", "count": 2, "name": "Spring of the Blue Chip", "nameRu": "Весна голубой фишки", "effect": {"kind": "summon", "cardId": "blue-chip-basilisk"}},
    "text": "Battlecry: summon a 1/1 Pixel Squire if a slot is free. Combo — if at least 2 other NFT fighters survived the opponent’s turn, summon a 4/3 Blue-Chip Basilisk with Rush if a slot is free instead of the ordinary Battlecry. Spring returns with a second edition.",
  },
  "relay-page": {
    "id": "relay-page", "name": "Relay Page",
    "faction": "DePIN", "rarity": "common", "cost": 1, "type": "minion",
    "attack": 1, "health": 1,
    "battlecry": {"kind": "heal-treasury", "amount": 1},
    "text": "Battlecry: restore 1 health to your treasury. First packet of the day: gm.",
  },
  "copper-lineworker": {
    "id": "copper-lineworker", "name": "Copper Lineworker",
    "faction": "DePIN", "rarity": "common", "cost": 2, "type": "minion",
    "attack": 1, "health": 1,
    "battlecry": {"kind": "heal-own-minions", "amount": 1},
    "ultimate": {"faction": "DePIN", "condition": "faction-plays", "count": 1, "name": "Copper Continuity", "nameRu": "Медная непрерывность", "effect": {"kind": "buff-own", "attack": 0, "health": 1}},
    "text": "Battlecry: restore up to 1 health to every friendly fighter. Combo — if you already played at least 1 DePIN card this turn, give every friendly fighter +0/+1 instead of the ordinary Battlecry. One earlier node turns a loose wire into a network.",
  },
  "beacon-scout": {
    "id": "beacon-scout", "name": "Beacon Scout",
    "faction": "DePIN", "rarity": "common", "cost": 3, "type": "minion",
    "attack": 2, "health": 2, "rush": true,
    "text": "Rush. Zero latency. Brief life expectancy.",
  },
  "ceramic-cachekeeper": {
    "id": "ceramic-cachekeeper", "name": "Ceramic Cachekeeper",
    "faction": "DePIN", "rarity": "common", "cost": 2, "type": "minion",
    "attack": 1, "health": 2,
    "ultimate": {"faction": "DePIN", "condition": "faction-allies", "count": 1, "name": "Cache Hit", "nameRu": "Попадание в кеш", "effect": {"kind": "draw", "amount": 1}},
    "text": "Combo — if at least 1 other DePIN fighter survived the opponent’s turn, draw 1 card. Cached yesterday. Useful today.",
  },
  "bridge-riveter": {
    "id": "bridge-riveter", "name": "Bridge Riveter",
    "faction": "DePIN", "rarity": "common", "cost": 3, "type": "minion",
    "attack": 1, "health": 3, "taunt": true,
    "battlecry": {"kind": "heal-own-minions", "amount": 1},
    "text": "Taunt. Battlecry: restore up to 1 health to every friendly fighter. Maintenance is cheaper than rebuilding the bridge.",
  },
  "signal-oracle": {
    "id": "signal-oracle", "name": "Signal Oracle",
    "faction": "DePIN", "rarity": "rare", "cost": 5, "type": "minion",
    "attack": 2, "health": 3,
    "battlecry": {"kind": "draw", "amount": 1},
    "ultimate": {"faction": "DePIN", "condition": "faction-plays", "count": 2, "name": "Triangulated Alpha", "nameRu": "Триангуляция альфы", "effect": {"kind": "draw", "amount": 3}},
    "text": "Battlecry: draw 1 card. Combo — if you already played at least 2 DePIN cards this turn, draw 3 cards instead of the ordinary Battlecry. Three packets, one very clear signal.",
  },
  "mesh-shieldbearer": {
    "id": "mesh-shieldbearer", "name": "Mesh Shieldbearer",
    "faction": "DePIN", "rarity": "rare", "cost": 4, "type": "minion",
    "attack": 2, "health": 3, "taunt": true,
    "ultimate": {"faction": "DePIN", "condition": "faction-plays", "count": 1, "name": "Mesh Redundancy", "nameRu": "Резерв mesh-сети", "effect": {"kind": "buff-own", "attack": 0, "health": 1}},
    "text": "Taunt. Combo — if you already played at least 1 DePIN card this turn, give every friendly fighter +0/+1. A second node makes the mesh harder to break.",
  },
  "agora-sitewarden": {
    "id": "agora-sitewarden", "name": "Agora Sitewarden",
    "faction": "DePIN", "rarity": "rare", "cost": 4, "type": "minion",
    "attack": 1, "health": 3,
    "battlecry": {"kind": "expand-board", "amount": 1},
    "text": "Battlecry: permanently add one fighter slot, up to seven. One more public slot. No infinite scalability promises.",
  },
  "packet-ferryman": {
    "id": "packet-ferryman", "name": "Packet Ferryman",
    "faction": "DePIN", "rarity": "rare", "cost": 3, "type": "minion",
    "attack": 2, "health": 1,
    "battlecry": {"kind": "summon", "cardId": "antenna-auxilia"},
    "ultimate": {"faction": "DePIN", "condition": "faction-plays", "count": 1, "name": "Mesh Crossing", "nameRu": "Переправа mesh-сети", "effect": {"kind": "summon", "cardId": "mesh-messenger"}},
    "text": "Battlecry: summon a 1/1 Antenna Auxilia if a slot is free. Combo — if you already played at least 1 DePIN card this turn, summon a 1/2 Mesh Messenger if a slot is free instead of the ordinary Battlecry. The fare includes one passenger.",
  },
  "atlas-nodebearer": {
    "id": "atlas-nodebearer", "name": "Atlas the Nodebearer",
    "faction": "DePIN", "rarity": "epic", "cost": 6, "type": "minion",
    "attack": 3, "health": 5, "taunt": true,
    "ultimate": {"faction": "DePIN", "condition": "faction-allies", "count": 2, "name": "Load-Bearing Network", "nameRu": "Несущая сеть", "effect": {"kind": "heal-own-minions", "amount": 4}},
    "text": "Taunt. Combo — if at least 2 other DePIN fighters survived the opponent’s turn, restore up to 4 health to every friendly fighter. The network stays up if somebody carries it.",
  },
  "daedalus-protocolwright": {
    "id": "daedalus-protocolwright", "name": "Daedalus the Protocolwright",
    "faction": "DePIN", "rarity": "epic", "cost": 5, "type": "minion",
    "attack": 2, "health": 3,
    "battlecry": {"kind": "summon", "cardId": "antenna-auxilia"},
    "ultimate": {"faction": "DePIN", "condition": "faction-allies", "count": 2, "name": "Hoplite Protocol", "nameRu": "Протокол гоплита", "effect": {"kind": "summon", "cardId": "hotspot-hoplite"}},
    "text": "Battlecry: summon a 1/1 Antenna Auxilia if a slot is free. Combo — if at least 2 other DePIN fighters survived the opponent’s turn, summon a 1/4 Hotspot Hoplite with Taunt if a slot is free instead of the ordinary Battlecry. One helper, properly maintained. Not an infinite factory.",
  },
  "hephaestus-public-nodes": {
    "id": "hephaestus-public-nodes", "name": "Hephaestus of Public Nodes",
    "faction": "DePIN", "rarity": "legendary", "cost": 8, "type": "minion",
    "attack": 4, "health": 5,
    "battlecry": {"kind": "buff-own", "attack": 0, "health": 1},
    "ultimate": {"faction": "DePIN", "condition": "faction-allies", "count": 2, "name": "Forge of Public Nodes", "nameRu": "Кузня общественных узлов", "effect": {"kind": "buff-own", "attack": 2, "health": 2}},
    "text": "Battlecry: give every friendly fighter +0/+1. Combo — if at least 2 other DePIN fighters survived the opponent’s turn, give every friendly fighter +2/+2 instead of the ordinary Battlecry. Public infrastructure earns a legendary upgrade.",
  },
  "copium-jester": {
    "id": "copium-jester", "name": "Copium Jester",
    "faction": "Meme", "rarity": "common", "cost": 1, "type": "minion",
    "attack": 1, "health": 1,
    "ultimate": {"faction": "Meme", "condition": "faction-plays", "count": 1, "name": "Cope Harder", "nameRu": "Копиум покрепче", "effect": {"kind": "damage-enemy-treasury", "amount": 1}},
    "text": "Combo — if you already played at least 1 Meme card this turn, deal 1 damage to the enemy treasury. It is only a loss if the punchline fails.",
  },
  "liquidity-goose": {
    "id": "liquidity-goose", "name": "Exit Liquidity Goose",
    "faction": "Meme", "rarity": "common", "cost": 2, "type": "minion",
    "attack": 2, "health": 1,
    "battlecry": {"kind": "damage-enemy-treasury", "amount": 1},
    "text": "Battlecry: deal 1 damage to the enemy treasury. Honk if you bought the top.",
  },
  "bagholder-donkey": {
    "id": "bagholder-donkey", "name": "Bagholder Donkey",
    "faction": "Meme", "rarity": "common", "cost": 3, "type": "minion",
    "attack": 1, "health": 4, "taunt": true,
    "text": "Taunt. Still holding. Mostly because he cannot move.",
  },
  "gm-rooster": {
    "id": "gm-rooster", "name": "GM Rooster",
    "faction": "Meme", "rarity": "common", "cost": 1, "type": "minion",
    "attack": 0, "health": 2,
    "battlecry": {"kind": "heal-treasury", "amount": 2},
    "text": "Battlecry: restore 2 health to your treasury. Wake up. The treasury needs you.",
  },
  "paperhand-merchant": {
    "id": "paperhand-merchant", "name": "Paperhand Merchant",
    "faction": "Meme", "rarity": "common", "cost": 2, "type": "minion",
    "attack": 1, "health": 1,
    "battlecry": {"kind": "gain-gas", "amount": 1},
    "text": "Battlecry: gain 1 order this turn. Sold the bag. Bought one more order.",
  },
  "fomo-trumpeter": {
    "id": "fomo-trumpeter", "name": "FOMO Trumpeter",
    "faction": "Meme", "rarity": "rare", "cost": 4, "type": "minion",
    "attack": 2, "health": 2,
    "battlecry": {"kind": "buff-own", "attack": 1, "health": 0},
    "ultimate": {"faction": "Meme", "condition": "faction-plays", "count": 2, "name": "Full FOMO Chorus", "nameRu": "Полный хор FOMO", "effect": {"kind": "buff-own", "attack": 1, "health": 1}},
    "text": "Battlecry: give every friendly fighter +1/+0. Combo — if you already played at least 2 Meme cards this turn, give every friendly fighter +1/+1 instead of the ordinary Battlecry. The third call is when everybody joins.",
  },
  "diamond-paw-mastiff": {
    "id": "diamond-paw-mastiff", "name": "Diamond Paw Mastiff",
    "faction": "Meme", "rarity": "rare", "cost": 4, "type": "minion",
    "attack": 2, "health": 3, "taunt": true, "lifesteal": true,
    "text": "Taunt. Lifesteal. Good boy. Bad exit liquidity.",
  },
  "hopium-augur": {
    "id": "hopium-augur", "name": "Hopium Augur",
    "faction": "Meme", "rarity": "rare", "cost": 4, "type": "minion",
    "attack": 1, "health": 3, "taunt": true,
    "battlecry": {"kind": "draw", "amount": 1},
    "ultimate": {"faction": "Meme", "condition": "faction-plays", "count": 2, "name": "Hopium Confirmed", "nameRu": "Хопиум подтверждён", "effect": {"kind": "draw", "amount": 2}},
    "text": "Taunt. Battlecry: draw 1 card. Combo — if you already played at least 2 Meme cards this turn, draw 2 cards instead of the ordinary Battlecry. Reads three omens. Keeps the receipts.",
  },
  "salt-miner-satyr": {
    "id": "salt-miner-satyr", "name": "Salt Miner Satyr",
    "faction": "Meme", "rarity": "rare", "cost": 4, "type": "minion",
    "attack": 3, "health": 2, "rush": true,
    "battlecry": {"kind": "weaken-random-enemy", "amount": 1},
    "text": "Rush. Battlecry: reduce a random enemy fighter’s attack by 1, to a minimum of 0. Harvests salt before the counterattack.",
  },
  "sir-rug-of-velvet": {
    "id": "sir-rug-of-velvet", "name": "Sir Rug of Velvet",
    "faction": "Meme", "rarity": "epic", "cost": 6, "type": "minion",
    "attack": 3, "health": 4, "lifesteal": true,
    "battlecry": {"kind": "damage-random-enemy", "amount": 1},
    "ultimate": {"faction": "Meme", "condition": "faction-plays", "count": 1, "name": "Velvet Exit", "nameRu": "Бархатный выход", "effect": {"kind": "damage-random-enemy", "amount": 3}},
    "text": "Lifesteal. Battlecry: deal 1 damage to a random enemy fighter, or their treasury if there are none. Combo — if you already played at least 1 Meme card this turn, deal 3 damage to a random enemy fighter, or their treasury if there are none instead of the ordinary Battlecry. A velvet rug is still a rug.",
  },
  "sisyphus-of-the-pump": {
    "id": "sisyphus-of-the-pump", "name": "Sisyphus of the Pump",
    "faction": "Meme", "rarity": "epic", "cost": 5, "type": "minion",
    "attack": 2, "health": 4, "halvingPeriod": 3,
    "battlecry": {"kind": "heal-treasury", "amount": 2},
    "text": "Every 3 blocks: +1/+1. Battlecry: restore 2 health to your treasury. Another block. Another hill. Still pumping.",
  },
  "dionysus-last-pump": {
    "id": "dionysus-last-pump", "name": "Dionysus of the Last Pump",
    "faction": "Meme", "rarity": "legendary", "cost": 8, "type": "minion",
    "attack": 4, "health": 4, "rush": true,
    "battlecry": {"kind": "heal-treasury", "amount": 2},
    "ultimate": {"faction": "Meme", "condition": "faction-plays", "count": 2, "name": "Last Pump Revel", "nameRu": "Пир последнего пампа", "effect": {"kind": "buff-own", "attack": 2, "health": 1}},
    "text": "Rush. Battlecry: restore 2 health to your treasury. Combo — if you already played at least 2 Meme cards this turn, give every friendly fighter +2/+1 instead of the ordinary Battlecry. The last pump needs a party that survived the night.",
  },
};

export const CHARACTER_CARD_RU: Record<string, { name: string; text: string }> = {
  "collateral-squire": {"name": "Оруженосец залога", "text": "Провокация. Щит — залог. Смелость залогу не подлежит."},
  "reserve-matron": {"name": "Матрона резервов", "text": "При выходе: восстанавливает 1 здоровья вашей казне. Связка — если ваш боец пережил ход соперника и находится в стейкинге, восстанавливает 4 здоровья вашей казне вместо обычного эффекта выхода. Резервы нужны на чёрный блок."},
  "interest-shepherd": {"name": "Пастух процентов", "text": "Каждые 4 блока: +1/+1. Пока рынок спит, стадо компаундится."},
  "spread-duelist": {"name": "Дуэлянт спреда", "text": "Натиск. Похищение жизни. Забирает спред, а не честный бой."},
  "slippage-netter": {"name": "Ловец проскальзывания", "text": "При выходе: снижает атаку случайного бойца врага на 1, минимум до 0. Плотнее сеть — меньше проскальзывание."},
  "credit-lanternist": {"name": "Фонарщик кредита", "text": "При выходе: добирает карт: 1. Связка — если ваш боец пережил ход соперника и находится в стейкинге, добирает карт: 2 вместо обычного эффекта выхода. Читает мелкий шрифт при заёмном свете."},
  "amm-tidekeeper": {"name": "Хранитель прилива AMM", "text": "При выходе: восстанавливает до 1 здоровья всем вашим бойцам. Связка — если ваш боец пережил ход соперника и находится в стейкинге, все ваши бойцы получают +0/+1 вместо обычного эффекта выхода. Не даёт пулу превратиться в лужу."},
  "margin-hoplite": {"name": "Гоплит маржи", "text": "Провокация. Связка — если другой боец DeFi пережил ход соперника, снижает атаку случайного бойца врага на 2, минимум до 0. Его запас прочности окован бронзой."},
  "mempool-usher": {"name": "Распорядитель мемпула", "text": "При выходе: отменяет самый дорогой указ в очереди врага. Ваш дорогой указ не в списке гостей."},
  "liquidation-bailiff": {"name": "Пристав ликвидации", "text": "При выходе: наносит 1 урон случайному бойцу врага; если бойцов нет — его казне. Связка — если хотя бы 2 других бойца DeFi пережили ход соперника, наносит 4 урон случайному бойцу врага; если бойцов нет — его казне вместо обычного эффекта выхода. Взыскивает, когда легион удержал двор."},
  "delta-sphinx": {"name": "Сфинкс дельты", "text": "Провокация. Связка — если ваш боец пережил ход соперника и находится в стейкинге, добирает карт: 2. Загадка проста. Сохранить залог сложнее."},
  "oracle-of-solvency": {"name": "Оракул платёжеспособности", "text": "При выходе: даёт 1 приказ в этом ходу. Связка — если хотя бы 2 ваших бойца пережили ход соперника и находятся в стейкинге, даёт 3 приказа в этом ходу вместо обычного эффекта выхода. Предвидит одно: приказы вам ещё понадобятся."},
  "poseidon-deep-liquidity": {"name": "Посейдон глубокой ликвидности", "text": "Провокация. При выходе: восстанавливает 4 здоровья вашей казне. Связка — если хотя бы 2 ваших бойца пережили ход соперника и находятся в стейкинге, все ваши бойцы получают +1/+2 вместо обычного эффекта выхода. Прилив награждает тех, кто удержал якоря."},
  "clay-mint-apprentice": {"name": "Подмастерье глиняного минта", "text": "При выходе: восстанавливает до 1 здоровья всем вашим бойцам. Свежая глина. Свежая уверенность."},
  "provenance-scribe": {"name": "Писец происхождения", "text": "Связка — если другой боец NFT пережил ход соперника, добирает карт: 2. Уцелевший оригинал придаёт вес новому тиражу."},
  "mosaic-mender": {"name": "Реставратор мозаик", "text": "При выходе: восстанавливает до 2 здоровья всем вашим бойцам. Трещина — не флор."},
  "gallery-gatekeeper": {"name": "Привратник галереи", "text": "Провокация. Правым кликом дальше не пройти."},
  "patina-curator": {"name": "Куратор патины", "text": "Связка — если другой боец NFT пережил ход соперника, все ваши бойцы получают +0/+1. Пережить рынок — уже редкий признак."},
  "blank-canvas-sentinel": {"name": "Страж чистого холста", "text": "Каждые 5 блока: +1/+1. Незаконченный шедевр всё равно растёт."},
  "reveal-diviner": {"name": "Прорицатель раскрытия", "text": "При выходе: наносит 1 урон всем бойцам врага. Связка — если ранее в этом ходу разыграна хотя бы одна карта NFT, наносит 2 урон всем бойцам врага вместо обычного эффекта выхода. Второй минт раскрывает спрятанный огонь."},
  "soulbound-companion": {"name": "Соулбаунд-спутник", "text": "Провокация. Связка — если другой боец NFT пережил ход соперника, восстанавливает до 3 здоровья всем вашим бойцам. Остаётся ради друзей, а не ради флора."},
  "royalty-chorister": {"name": "Хорист роялти", "text": "При выходе: даёт 1 приказ в этом ходу. Связка — если ранее в этом ходу разыграна хотя бы одна карта NFT, даёт 2 приказа в этом ходу вместо обычного эффекта выхода. Хор платит один раз. Без вечных роялти."},
  "unbroken-marble-warden": {"name": "Страж цельного мрамора", "text": "Провокация. При выходе: восстанавливает 2 здоровья вашей казне. Связка — если хотя бы 2 других бойца NFT пережили ход соперника, все ваши бойцы получают +0/+2 вместо обычного эффекта выхода. Сохраняет коллекцию целой на медвежьем рынке."},
  "medusa-of-missing-mints": {"name": "Медуза пропущенных минтов", "text": "При выходе: снижает атаку случайного бойца врага на 2, минимум до 0. Связка — если ранее в этом ходу разыграна хотя бы одна карта NFT, снижает атаку случайного бойца врага на 4, минимум до 0 вместо обычного эффекта выхода. Пропустил минт? Попробуй шевельнуть бумажными руками."},
  "palimpsest-guardian": {"name": "Страж палимпсеста", "text": "Похищение жизни. Связка — если хотя бы 2 других бойца NFT пережили ход соперника, все ваши бойцы получают +1/+1. Пишет сильную армию поверх уцелевшего черновика."},
  "persephone-second-mint": {"name": "Персефона второго минта", "text": "При выходе: призывает Пиксельного оруженосца 1/1 при наличии свободного места. Связка — если хотя бы 2 других бойца NFT пережили ход соперника, призывает Василиска Blue Chip 4/3 с Натиском при наличии свободного места вместо обычного эффекта выхода. Весна возвращается вторым тиражом."},
  "relay-page": {"name": "Паж ретрансляции", "text": "При выходе: восстанавливает 1 здоровья вашей казне. Первый пакет дня: gm."},
  "copper-lineworker": {"name": "Монтажница медной линии", "text": "При выходе: восстанавливает до 1 здоровья всем вашим бойцам. Связка — если ранее в этом ходу разыграна хотя бы одна карта DePIN, все ваши бойцы получают +0/+1 вместо обычного эффекта выхода. Один узел превращает провод в сеть."},
  "beacon-scout": {"name": "Разведчик маяков", "text": "Натиск. Нулевая задержка. Короткий срок службы."},
  "ceramic-cachekeeper": {"name": "Хранитель керамического кеша", "text": "Связка — если другой боец DePIN пережил ход соперника, добирает карт: 1. Закешировал вчера. Пригодилось сегодня."},
  "bridge-riveter": {"name": "Клепальщик мостов", "text": "Провокация. При выходе: восстанавливает до 1 здоровья всем вашим бойцам. Обслужить мост дешевле, чем перестроить."},
  "signal-oracle": {"name": "Оракул сигнала", "text": "При выходе: добирает карт: 1. Связка — если ранее в этом ходу разыграны хотя бы две карты DePIN, добирает карт: 3 вместо обычного эффекта выхода. Три пакета. Один очень ясный сигнал."},
  "mesh-shieldbearer": {"name": "Щитоносец mesh-сети", "text": "Провокация. Связка — если ранее в этом ходу разыграна хотя бы одна карта DePIN, все ваши бойцы получают +0/+1. Второй узел укрепляет всю сеть."},
  "agora-sitewarden": {"name": "Смотритель стройки агоры", "text": "При выходе: навсегда добавляет одно место в строю, максимум до семи. Ещё одно место в строю. Без обещаний бесконечного скейла."},
  "packet-ferryman": {"name": "Паромщик пакетов", "text": "При выходе: призывает Антенного вспомогателя 1/1 при наличии свободного места. Связка — если ранее в этом ходу разыграна хотя бы одна карта DePIN, призывает Вестника mesh-сети 1/2 при наличии свободного места вместо обычного эффекта выхода. В стоимость входит один пассажир."},
  "atlas-nodebearer": {"name": "Атлант узлов", "text": "Провокация. Связка — если хотя бы 2 других бойца DePIN пережили ход соперника, восстанавливает до 4 здоровья всем вашим бойцам. Сеть работает, пока кто-то держит её на плечах."},
  "daedalus-protocolwright": {"name": "Дедал, мастер протоколов", "text": "При выходе: призывает Антенного вспомогателя 1/1 при наличии свободного места. Связка — если хотя бы 2 других бойца DePIN пережили ход соперника, призывает Гоплита хотспота 1/4 с Провокацией при наличии свободного места вместо обычного эффекта выхода. Один исправный помощник. Не бесконечная фабрика."},
  "hephaestus-public-nodes": {"name": "Гефест общественных узлов", "text": "При выходе: все ваши бойцы получают +0/+1. Связка — если хотя бы 2 других бойца DePIN пережили ход соперника, все ваши бойцы получают +2/+2 вместо обычного эффекта выхода. Общественная инфраструктура получает легендарный апгрейд."},
  "copium-jester": {"name": "Шут копиума", "text": "Связка — если ранее в этом ходу разыграна хотя бы одна карта Meme, наносит 1 урон казне врага. Это убыток, только если шутка не зашла."},
  "liquidity-goose": {"name": "Гусь выходной ликвидности", "text": "При выходе: наносит 1 урон казне врага. Посигналь, если купил на хаях."},
  "bagholder-donkey": {"name": "Осёл тяжёлых бэгов", "text": "Провокация. Всё ещё держит. В основном потому, что не может идти."},
  "gm-rooster": {"name": "Петух GM", "text": "При выходе: восстанавливает 2 здоровья вашей казне. Просыпайся. Казна зовёт."},
  "paperhand-merchant": {"name": "Торговец бумажных рук", "text": "При выходе: даёт 1 приказ в этом ходу. Продал бэг. Купил ещё один приказ."},
  "fomo-trumpeter": {"name": "Трубач FOMO", "text": "При выходе: все ваши бойцы получают +1/+0. Связка — если ранее в этом ходу разыграны хотя бы две карты Meme, все ваши бойцы получают +1/+1 вместо обычного эффекта выхода. На третий зов сбегаются все."},
  "diamond-paw-mastiff": {"name": "Мастиф алмазной лапы", "text": "Провокация. Похищение жизни. Хороший мальчик. Плохая выходная ликвидность."},
  "hopium-augur": {"name": "Авгур хопиума", "text": "Провокация. При выходе: добирает карт: 1. Связка — если ранее в этом ходу разыграны хотя бы две карты Meme, добирает карт: 2 вместо обычного эффекта выхода. Читает три знамения. Хранит чеки."},
  "salt-miner-satyr": {"name": "Сатир соляной шахты", "text": "Натиск. При выходе: снижает атаку случайного бойца врага на 1, минимум до 0. Собирает соль до ответного удара."},
  "sir-rug-of-velvet": {"name": "Сэр Раг Бархатный", "text": "Похищение жизни. При выходе: наносит 1 урон случайному бойцу врага; если бойцов нет — его казне. Связка — если ранее в этом ходу разыграна хотя бы одна карта Meme, наносит 3 урон случайному бойцу врага; если бойцов нет — его казне вместо обычного эффекта выхода. Бархатный раг всё равно остаётся рагом."},
  "sisyphus-of-the-pump": {"name": "Сизиф вечного пампа", "text": "Каждые 3 блока: +1/+1. При выходе: восстанавливает 2 здоровья вашей казне. Новый блок. Новая гора. Памп продолжается."},
  "dionysus-last-pump": {"name": "Дионис последнего пампа", "text": "Натиск. При выходе: восстанавливает 2 здоровья вашей казне. Связка — если ранее в этом ходу разыграны хотя бы две карты Meme, все ваши бойцы получают +2/+1 вместо обычного эффекта выхода. Последнему пампу нужна вечеринка, пережившая ночь."},
};

/** Original approved full-colour artwork; no placeholder art or new frame. */
export const CHARACTER_CARD_ART: Readonly<Record<string, string>> = {
  "collateral-squire": "/ui/arena-lab/character-art-50/art/01-collateral-squire.webp",
  "reserve-matron": "/ui/arena-lab/character-art-50/art/02-reserve-matron.webp",
  "interest-shepherd": "/ui/arena-lab/character-art-50/art/03-interest-shepherd.webp",
  "spread-duelist": "/ui/arena-lab/character-art-50/art/04-spread-duelist.webp",
  "slippage-netter": "/ui/arena-lab/character-art-50/art/05-slippage-netter.webp",
  "credit-lanternist": "/ui/arena-lab/character-art-50/art/06-credit-lanternist.webp",
  "amm-tidekeeper": "/ui/arena-lab/character-art-50/art/07-amm-tidekeeper.webp",
  "margin-hoplite": "/ui/arena-lab/character-art-50/art/08-margin-hoplite.webp",
  "mempool-usher": "/ui/arena-lab/character-art-50/art/09-mempool-usher.webp",
  "liquidation-bailiff": "/ui/arena-lab/character-art-50/art/10-liquidation-bailiff.webp",
  "delta-sphinx": "/ui/arena-lab/character-art-50/art/11-delta-sphinx.webp",
  "oracle-of-solvency": "/ui/arena-lab/character-art-50/art/12-oracle-of-solvency.webp",
  "poseidon-deep-liquidity": "/ui/arena-lab/character-art-50/art/13-poseidon-deep-liquidity.webp",
  "clay-mint-apprentice": "/ui/arena-lab/character-art-50/art/14-clay-mint-apprentice.webp",
  "provenance-scribe": "/ui/arena-lab/character-art-50/art/15-provenance-scribe.webp",
  "mosaic-mender": "/ui/arena-lab/character-art-50/art/16-mosaic-mender.webp",
  "gallery-gatekeeper": "/ui/arena-lab/character-art-50/art/17-gallery-gatekeeper.webp",
  "patina-curator": "/ui/arena-lab/character-art-50/art/18-patina-curator.webp",
  "blank-canvas-sentinel": "/ui/arena-lab/character-art-50/art/19-blank-canvas-sentinel.webp",
  "reveal-diviner": "/ui/arena-lab/character-art-50/art/20-reveal-diviner.webp",
  "soulbound-companion": "/ui/arena-lab/character-art-50/art/21-soulbound-companion.webp",
  "royalty-chorister": "/ui/arena-lab/character-art-50/art/22-royalty-chorister.webp",
  "unbroken-marble-warden": "/ui/arena-lab/character-art-50/art/23-unbroken-marble-warden.webp",
  "medusa-of-missing-mints": "/ui/arena-lab/character-art-50/art/24-medusa-of-missing-mints.webp",
  "palimpsest-guardian": "/ui/arena-lab/character-art-50/art/25-palimpsest-guardian.webp",
  "persephone-second-mint": "/ui/arena-lab/character-art-50/art/26-persephone-second-mint.webp",
  "relay-page": "/ui/arena-lab/character-art-50/art/27-relay-page.webp",
  "copper-lineworker": "/ui/arena-lab/character-art-50/art/28-copper-lineworker.webp",
  "beacon-scout": "/ui/arena-lab/character-art-50/art/29-beacon-scout.webp",
  "ceramic-cachekeeper": "/ui/arena-lab/character-art-50/art/30-ceramic-cachekeeper.webp",
  "bridge-riveter": "/ui/arena-lab/character-art-50/art/31-bridge-riveter.webp",
  "signal-oracle": "/ui/arena-lab/character-art-50/art/32-signal-oracle.webp",
  "mesh-shieldbearer": "/ui/arena-lab/character-art-50/art/33-mesh-shieldbearer.webp",
  "agora-sitewarden": "/ui/arena-lab/character-art-50/art/34-agora-sitewarden.webp",
  "packet-ferryman": "/ui/arena-lab/character-art-50/art/35-packet-ferryman.webp",
  "atlas-nodebearer": "/ui/arena-lab/character-art-50/art/36-atlas-nodebearer.webp",
  "daedalus-protocolwright": "/ui/arena-lab/character-art-50/art/37-daedalus-protocolwright.webp",
  "hephaestus-public-nodes": "/ui/arena-lab/character-art-50/art/38-hephaestus-public-nodes.webp",
  "copium-jester": "/ui/arena-lab/character-art-50/art/39-copium-jester.webp",
  "liquidity-goose": "/ui/arena-lab/character-art-50/art/40-liquidity-goose.webp",
  "bagholder-donkey": "/ui/arena-lab/character-art-50/art/41-bagholder-donkey.webp",
  "gm-rooster": "/ui/arena-lab/character-art-50/art/42-gm-rooster.webp",
  "paperhand-merchant": "/ui/arena-lab/character-art-50/art/43-paperhand-merchant.webp",
  "fomo-trumpeter": "/ui/arena-lab/character-art-50/art/44-fomo-trumpeter.webp",
  "diamond-paw-mastiff": "/ui/arena-lab/character-art-50/art/45-diamond-paw-mastiff.webp",
  "hopium-augur": "/ui/arena-lab/character-art-50/art/46-hopium-augur.webp",
  "salt-miner-satyr": "/ui/arena-lab/character-art-50/art/47-salt-miner-satyr.webp",
  "sir-rug-of-velvet": "/ui/arena-lab/character-art-50/art/48-sir-rug-of-velvet.webp",
  "sisyphus-of-the-pump": "/ui/arena-lab/character-art-50/art/49-sisyphus-of-the-pump.webp",
  "dionysus-last-pump": "/ui/arena-lab/character-art-50/art/50-dionysus-last-pump.webp",
};
