/**
 * IMPERIVM — Agora After Hours starter decks.
 *
 * One 30-card deck per hero. Max 2 copies per card, 1 copy per legendary.
 * Each deck leans into its hero's flavor but stays mixed-faction.
 *
 * All fifty Agora characters are available in these four main decks. Cheap
 * enablers have a second copy; conditional finishers remain singletons.
 * whale:     DeFi staking, weakening, market control and treasury recovery.
 * builder:   NFT preservation, wounded-fighter recovery and surviving allies.
 * degen:     Meme play sequences, pressure and deliberate hand management.
 * validator: DePIN relay sequences, order income and expanded board space.
 */
export const DECKS: Record<string, string[]> = {
  whale: [
    'collateral-squire',
    'collateral-squire',
    'reserve-matron',
    'interest-shepherd',
    'interest-shepherd',
    'spread-duelist',
    'spread-duelist',
    'slippage-netter',
    'slippage-netter',
    'credit-lanternist',
    'credit-lanternist',
    'amm-tidekeeper',
    'margin-hoplite',
    'mempool-usher',
    'liquidation-bailiff',
    'delta-sphinx',
    'oracle-of-solvency',
    'poseidon-deep-liquidity',
    'amm-centurion',
    'priority-fee',
    'priority-fee',
    'flash-loan',
    'flash-loan',
    'senate-censure',
    'senate-censure',
    'staking-pool',
    'staking-pool',
    'impermanent-guard',
    'zeus-liquidator',
    'rug-pull',
  ],
  builder: [
    'clay-mint-apprentice',
    'clay-mint-apprentice',
    'provenance-scribe',
    'provenance-scribe',
    'mosaic-mender',
    'mosaic-mender',
    'gallery-gatekeeper',
    'gallery-gatekeeper',
    'patina-curator',
    'patina-curator',
    'blank-canvas-sentinel',
    'reveal-diviner',
    'soulbound-companion',
    'royalty-chorister',
    'unbroken-marble-warden',
    'medusa-of-missing-mints',
    'palimpsest-guardian',
    'persephone-second-mint',
    'whitelist-scout',
    'whitelist-scout',
    'profile-pic-phalanx',
    'agora-expansion',
    'diamond-aegis',
    'diamond-aegis',
    'restoration-rite',
    'restoration-rite',
    'trait-reroll',
    'flash-loan',
    'minting-press',
    'athena-diamond-guard',
  ],
  degen: [
    'copium-jester',
    'copium-jester',
    'liquidity-goose',
    'liquidity-goose',
    'bagholder-donkey',
    'bagholder-donkey',
    'gm-rooster',
    'gm-rooster',
    'paperhand-merchant',
    'paperhand-merchant',
    'fomo-trumpeter',
    'diamond-paw-mastiff',
    'hopium-augur',
    'hopium-augur',
    'salt-miner-satyr',
    'sir-rug-of-velvet',
    'sisyphus-of-the-pump',
    'dionysus-last-pump',
    'gm-greeter',
    'gm-greeter',
    'dogen',
    'dogen',
    'priority-fee',
    'priority-fee',
    'flash-loan',
    'flash-loan',
    'solar-sapper',
    'solar-sapper',
    'to-the-moon-militia',
    'hades-rugkeeper',
  ],
  validator: [
    'relay-page',
    'relay-page',
    'copper-lineworker',
    'copper-lineworker',
    'beacon-scout',
    'beacon-scout',
    'ceramic-cachekeeper',
    'ceramic-cachekeeper',
    'bridge-riveter',
    'bridge-riveter',
    'signal-oracle',
    'mesh-shieldbearer',
    'mesh-shieldbearer',
    'agora-sitewarden',
    'packet-ferryman',
    'atlas-nodebearer',
    'daedalus-protocolwright',
    'hephaestus-public-nodes',
    'priority-fee',
    'priority-fee',
    'antenna-auxilia',
    'antenna-auxilia',
    'agora-expansion',
    'agora-expansion',
    'node-sentinel',
    'hermes-relayer',
    'hermes-relayer',
    'flash-loan',
    'firmware-phalanx',
    'audit',
  ],
};

// New rulers start from proven faction curves; no existing card is removed.
DECKS.strategist=[...DECKS.builder];
DECKS.athena=[...DECKS.builder];
DECKS.hermes=[...DECKS.validator];
DECKS.hephaestus=[...DECKS.validator];
DECKS.poseidon=[...DECKS.whale];
