import {installDelayedSpellFixtures} from './delayed-spell-fixtures';
import assert from 'node:assert/strict';
import {createGame,applyAction,legalActions,effectivePowerCost} from '../lib/engine/engine';
import {pendingValidatorOrders,rulesetOf} from '../lib/engine/ruleset';
import {DECKS} from '../lib/decks';
import {diffAction} from '../lib/events';
import type {Action,GameState} from '../lib/engine/types';
import {GameSession,createLabGame,type PresentationBatch} from '../components/presentation/GameSession';
import {videoCues} from '../components/presentation/videoCue';
import {abilityCues} from '../components/presentation/abilityCues';
import {battleFloats} from '../components/presentation/battleFloats';
import {effectTimeline} from '../components/presentation/effectTimeline';

const classic=createGame('validator',DECKS.validator,'degen',DECKS.degen,42);
assert.deepEqual(classic,createGame('validator',DECKS.validator,'degen',DECKS.degen,{ruleset:'classic-v1'},42));
classic.players[0].gas=2;
assert.equal(applyAction(classic,{type:'hero-power'}).players[0].gas,1,'Validator reserves orders instead of an immediate refund');
assert.equal(applyAction(classic,{type:'hero-power'}).players[0].powerIncome,2);
assert.equal(rulesetOf(classic),'classic-v1');

const experiment=()=>createGame('validator',DECKS.validator,'degen',DECKS.degen,{ruleset:'validator-investment-v1'},42);
const batch=(before:GameState,action:Action):PresentationBatch=>{const after=applyAction(before,action);return {id:1,revision:1,action,before,after,events:diffAction(before,after,action)};};
let state=experiment();state.players[0].gas=3;state.players[0].maxGas=2;
state.players[0].hand=[{uid:'fee',cardId:'priority-fee'},{uid:'income',cardId:'amm-centurion'}];
state=applyAction(state,{type:'cast-spell',uid:'fee'});
state=applyAction(state,{type:'play-minion',uid:'income'});
state=applyAction(state,{type:'stake',uid:state.players[0].board[0].uid});
const original=structuredClone(state),reservation=batch(state,{type:'hero-power'});state=reservation.after;
assert.deepEqual(reservation.before,original,'Payment and reservation must not mutate the input');
assert.equal(state.players[0].gas,0);assert.equal(pendingValidatorOrders(state,0),2);
assert(!legalActions(state).some(a=>a.type==='hero-power'));
assert.throws(()=>applyAction(state,{type:'hero-power'}));
assert.equal(videoCues(reservation).length,0,'No gain-of-orders video during reservation');
assert(!battleFloats(reservation).some(c=>c.kind==='gas'));
assert(abilityCues(reservation).some(c=>c.kind==='seal'&&c.to==='hero-0'));
state=applyAction(state,{type:'end-turn'});
assert.equal(pendingValidatorOrders(state,0),2,'Income waits through the enemy turn');
const payout=batch(JSON.parse(JSON.stringify(state)),{type:'end-turn'});state=payout.after;
assert.equal(state.players[0].gas,7,'Base 3 + staked 1 + queued 1 + investment 2');
assert.equal(pendingValidatorOrders(state,0),0);
assert.deepEqual(battleFloats(payout).filter(c=>c.kind==='gas'),[{anchor:'gas-counter',label:'+2',kind:'gas',wave:'aftermath'}]);
assert(videoCues(payout).some(c=>c.id==='05-validator-gas'&&c.wave==='aftermath'));
const timeline=effectTimeline(payout)!;
assert(timeline.windows.findIndex(w=>w.key==='aftermath')>timeline.windows.findIndex(w=>w.key.startsWith('queued-')),'Income contact follows queued edicts');
state=applyAction(applyAction(state,{type:'end-turn'}),{type:'end-turn'});
assert.equal(state.players[0].gas,5,'Unspent bonus expires; no second payout');

let capped=experiment();capped.players[0].gas=2;capped.players[0].maxGas=10;
capped=applyAction(applyAction(applyAction(capped,{type:'hero-power'}),{type:'end-turn'}),{type:'end-turn'});
assert.equal(capped.players[0].gas,12);assert.equal(capped.players[0].maxGas,10);
let comeback=experiment();comeback.players[0].treasury=10;comeback.players[0].gas=1;
assert.equal(effectivePowerCost(comeback,0),1);
comeback=applyAction(comeback,{type:'hero-power'});assert.equal(comeback.players[0].gas,0);assert.equal(pendingValidatorOrders(comeback,0),2);

const restoreDelayedFixtures=installDelayedSpellFixtures(['flash-loan']);
let earlyLethal=experiment();earlyLethal.players[0].gas=6;earlyLethal.players[0].hand=[{uid:'draw',cardId:'delayed-fixture-flash-loan'}];
earlyLethal=applyAction(earlyLethal,{type:'cast-spell',uid:'draw'});
earlyLethal=applyAction(earlyLethal,{type:'hero-power'});
earlyLethal.players[0].deck=[];earlyLethal.players[0].treasury=1;
earlyLethal=applyAction(earlyLethal,{type:'end-turn'});
const lethal=batch(earlyLethal,{type:'end-turn'});
assert.equal(lethal.after.winner,1);assert.equal(pendingValidatorOrders(lethal.after,0),2,'Lethal queued draw ends the game before refill/income');
assert(!videoCues(lethal).some(c=>c.id==='05-validator-gas'));
restoreDelayedFixtures();

let opposite=createGame('builder',DECKS.builder,'validator',DECKS.validator,{ruleset:'validator-investment-v1'},42);
opposite=applyAction(opposite,{type:'end-turn'});opposite.players[1].gas=2;
opposite=applyAction(opposite,{type:'hero-power'});opposite=applyAction(opposite,{type:'end-turn'});
const p1Payout=batch(opposite,{type:'end-turn'});
assert.equal(pendingValidatorOrders(p1Payout.after,1),0);
assert(battleFloats(p1Payout).some(c=>c.anchor==='hero-1'&&c.label==='+2'));
const session=new GameSession(reservation.before),queued=session.dispatch({type:'hero-power'})!;
session.restart(createLabGame('validator',true,42,'degen','validator-investment-v1'));
session.impact(queued.id);session.complete(queued.id);
assert.equal(pendingValidatorOrders(session.snapshot().state,0),0,'Restart cannot carry an investment or stale callback');
console.log('PASS optional Validator investment: legacy equivalence, full payment, once per turn, own-turn payout, queued + staked rewards, serialization, overflow, comeback, lethal stop, both seats, restart and honest effect timing');
