/** Nine permanent free 30-card deck recipes. Five rulers are available initially. Paid Agora recipes live separately in lib/decks.ts. */
export const FREE_DECKS: Record<string, string[]> = {
  whale: [
    'lending-legionnaire',
    'lending-legionnaire',
    'amm-centurion',
    'amm-centurion',
    'liquidation-officer',
    'liquidation-officer',
    'frontrun-bot',
    'frontrun-bot',
    'priority-fee',
    'priority-fee',
    'flash-loan',
    'flash-loan',
    'solar-sapper',
    'solar-sapper',
    'reveal-ceremony',
    'reveal-ceremony',
    'gps-gladiator',
    'gps-gladiator',
    'staking-pool',
    'staking-pool',
    'yield-farmer',
    'yield-farmer',
    'impermanent-guard',
    'impermanent-guard',
    'blue-chip-basilisk',
    'blue-chip-basilisk',
    'trait-reroll',
    'fud-hydra',
    'zeus-liquidator',
    'rug-pull',
  ],
  builder: [
    'gm-greeter',
    'gm-greeter',
    'antenna-auxilia',
    'antenna-auxilia',
    'pixel-squire',
    'pixel-squire',
    'whitelist-scout',
    'whitelist-scout',
    'mesh-messenger',
    'mesh-messenger',
    'profile-pic-phalanx',
    'profile-pic-phalanx',
    'floor-sweeper',
    'floor-sweeper',
    'relay-runner',
    'relay-runner',
    'node-sentinel',
    'node-sentinel',
    'hotspot-hoplite',
    'hotspot-hoplite',
    'agora-expansion',
    'agora-expansion',
    'diamond-aegis',
    'senate-censure',
    'firmware-phalanx',
    'firmware-phalanx',
    'impermanent-guard',
    'impermanent-guard',
    'minting-press',
    'athena-diamond-guard',
  ],
  degen: [
    'jeet-legion',
    'jeet-legion',
    'gm-greeter',
    'gm-greeter',
    'dogen',
    'dogen',
    'sandwich-attacker',
    'sandwich-attacker',
    'pepito',
    'pepito',
    'pump-chaser',
    'pump-chaser',
    'liquidation-officer',
    'liquidation-officer',
    'frontrun-bot',
    'frontrun-bot',
    'priority-fee',
    'flash-loan',
    'flash-loan',
    'diamond-hoarder',
    'diamond-hoarder',
    'solar-sapper',
    'solar-sapper',
    'gps-gladiator',
    'gps-gladiator',
    'fud-hydra',
    'fud-hydra',
    'to-the-moon-militia',
    'to-the-moon-militia',
    'hades-rugkeeper',
  ],
  validator: [
    'priority-fee',
    'priority-fee',
    'frontrun-bot',
    'frontrun-bot',
    'antenna-auxilia',
    'antenna-auxilia',
    'lending-legionnaire',
    'lending-legionnaire',
    'amm-centurion',
    'amm-centurion',
    'node-sentinel',
    'node-sentinel',
    'yield-farmer',
    'yield-farmer',
    'ape-praetorian',
    'ape-praetorian',
    'hermes-relayer',
    'hermes-relayer',
    'hotspot-hoplite',
    'hotspot-hoplite',
    'staking-pool',
    'staking-pool',
    'flash-loan',
    'flash-loan',
    'gps-gladiator',
    'gps-gladiator',
    'firmware-phalanx',
    'firmware-phalanx',
    'audit',
    'zeus-liquidator',
  ],
};

// New rulers start from proven faction curves; no existing card is removed.
FREE_DECKS.strategist=[...FREE_DECKS.builder];
FREE_DECKS.athena=[...FREE_DECKS.builder];
FREE_DECKS.hermes=[...FREE_DECKS.validator];
FREE_DECKS.hephaestus=[...FREE_DECKS.validator];
FREE_DECKS.poseidon=[...FREE_DECKS.whale];

/** Equal opening curves: six one-order fighters, counterplay and a real
 * finisher. The former recipes above remain in source; saved user decks
 * are never rewritten. Faction substitutions share cost and copy limits. */
const balancedStarter=[
  'lending-legionnaire','lending-legionnaire','antenna-auxilia','antenna-auxilia','gm-greeter','gm-greeter',
  'amm-centurion','amm-centurion','mesh-messenger','mesh-messenger','profile-pic-phalanx','profile-pic-phalanx',
  'relay-runner','relay-runner','yield-farmer','yield-farmer','floor-sweeper','floor-sweeper',
  'hotspot-hoplite','hotspot-hoplite','gps-gladiator','gps-gladiator','firmware-phalanx','firmware-phalanx',
  'flash-loan','flash-loan','agora-expansion','solar-sapper','diamond-aegis','imperator-liquidus',
];
const swaps:Record<string,Record<string,string>>={
  whale:{'floor-sweeper':'liquidation-officer'},builder:{'yield-farmer':'node-sentinel'},degen:{'mesh-messenger':'dogen'},
  validator:{'floor-sweeper':'hermes-relayer'},strategist:{'yield-farmer':'node-sentinel'},athena:{'yield-farmer':'node-sentinel'},
  hermes:{'floor-sweeper':'hermes-relayer'},hephaestus:{'hotspot-hoplite':'staking-pool'},poseidon:{'floor-sweeper':'liquidation-officer'},
};
for(const [hero,substitutions] of Object.entries(swaps))FREE_DECKS[hero]=balancedStarter.map(id=>substitutions[id]??id);
